---
## Default Kibana configuration from kibana-docker.
## https://github.com/elastic/kibana-docker/blob/master/.tedi/template/kibana.yml.j2
#
server.name: kibana
server.host: "0"
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
# disable monitoring feature
# xpack.monitoring.ui.container.elasticsearch.enabled: false

## X-Pack security credentials
#
# elasticsearch.username: elastic
# elasticsearch.password: changeme